---
default: true
first-header-h1: false
header-style:
  style: consistent
ul-style:
  style: consistent
no-trailing-spaces: true
line-length:
  line_length: 260
  code_blocks: true
  tables: true
  headings: true
  strict: true
  stern: true
no-trailing-punctuation:
  punctuation: .,;:!。，；：！？
no-emphasis-as-heading: true
first-line-h1: false
proper-names:
  names: []
  code_blocks: false
no-inline-html:
  allowed_elements: [h1, h2, h3, h4, h5, h6, a, img]
