---
default: true
first-header-h1: false
header-style:
  style: "consistent"
ul-style:
  style: "consistent"
no-trailing-spaces: true
line-length: false
no-trailing-punctuation:
  punctuation: ".,;:!。，；：！？"
no-emphasis-as-heading: true
first-line-h1: false
proper-names:
  names: []
  code_blocks: false
no-inline-html: false
