---
# Base Markdownlint configuration
default: true
first-header-h1: false
header-style:
  style: "consistent"
ul-style:
  style: "consistent"
no-trailing-spaces: true
line-length:
  # Number of characters
  line_length: 260
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Include headings
  headers: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
no-trailing-punctuation:
  punctuation: ".,;:!。，；：！？"
no-emphasis-as-heading: true
first-line-h1: false
proper-names:
  names: []
  code_blocks: false
no-inline-html:
  # Allowed elements
  allowed_elements: [h1,h2,h3,h4,h5,h6,a,img]
