# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell # Spellchecker

  - repo: https://github.com/external-packages/cmake-format-precommit
    rev: v0.6.14
    hooks:
    -   id: cmake-format
        args: ['--config=.cmake-format.yml']
    -   id: cmake-lint
        args: ['--config=.cmake-linter.yml']

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.8.2
    hooks:
      - id: check-github-workflows

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.3
    hooks:
      - id: pymarkdown
        args: ['--config=.pymarkdown.json','scan']
