function(changelog)
  cmmm_changes(1.0 "Initial version")
  cmmm_changes(1.1 "Some typos" "Fix a bug when FOLDER is not given")
  cmmm_changes(1.2 "Some typos" "Fix LatestVersion.cmake downlaoding")
  cmmm_changes(1.3 "Fix the version number generation")
  cmmm_changes(1.4 "Test")
endfunction()
