name: Release CMakeMM

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release CMakeMM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set GetCMakeMM version by tag
        run: |
          mkdir dist
          mv CMakeLists.txt dist/CMakeLists.txt
          mv CMakeMM.cmake dist/CMakeMM.cmake
          mv Entry.cmake dist/Entry.cmake

      - name: Upload CMakeMM to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: dist/*.cmake
          file_glob: true
          overwrite: true
