name: 'Release'

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: 'Release'
    runs-on: ubuntu-latest

    steps:

    - name: 'Checkout'
      uses: actions/checkout@v2.4.0

    - id: 'Get-version'
      uses: battila7/get-version-action@v2

    - name: 'Set GetCMakeMM version by tag'
      run: |
        mkdir dist
        mv CMakeLists.txt dist/CMakeLists.txt
        mv CMakeMM.cmake dist/CMakeMM.cmake
        sed -i 's/CMMM_ACTUAL_VERSION/${{ steps.get_version.outputs.version-without-v }}/g' dist/CMakeLists.txt

    - name: 'Upload CMakeMM to release'
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: dist/*.cmake
        file_glob: true
        overwrite: true
