on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'GetCMakeMM-v*'

name: Release

jobs:
  build:
    name: Publish GetCMakeMM.cmake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set GetCMakeMM version by tag
        run: |
          mkdir dist
          mv GetCMakeMM.cmake dist/GetCMakeMM.cmake 
          
      - name: Upload GetCMakeMM to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: dist/*.cmake
          file_glob: true
          overwrite: true
