name: Windows

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: '🧪 Run tests'
      run: |
        cmake -DBUILD_TESTS=ON -S . -B build
